#!/usr/bin/perl
use Dancer;
use JSON;

# init
my $version = '0.1';

# POST hook-receiver per project
post '/hook/:project' => sub {

    # payload is mandatory
    my $payload = params->{'payload'};
    if (not defined $payload) {
        status '404';
        return "Hmm, no payload in your backpack dude\n";
    }

    # inspect the data submitted
    my $json = from_json($payload);
    my $repo = $json->{repository};
    my $commits = $json->{commits};

    my $queue = config->{'queue_file'};
    my $prefix = config->{'prefix'};

    open my $fh, '>>', $queue or 
        status 500 && return "unable to open $queue";
    print $fh $prefix."[".$repo->{name}."] "
        . scalar(@$commits) . " commit(s) pushed "
        . $repo->{url}."\n";
    close $fh;
};

dance;
